---
- hosts: all
  become: yes
  tasks:
    - name: Installeer Apache
      apt:
        name: apache2
        state: present

    - name: Apache starten
      service:
        name: apache2
        state: started
        enabled: true